import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const cliDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repository = resolve(cliDirectory, "..", "..");
const result = await build({
  entryPoints: [resolve(repository, "apps/relay/src/index.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2024",
  write: false,
  legalComments: "none",
  sourcemap: false,
});
const output = result.outputFiles?.[0];
if (output === undefined) {
  throw new Error("Relay bundling did not produce an artifact.");
}
const source = output.text;
const sha256 = createHash("sha256").update(source).digest("hex");
const generated = `// Generated by scripts/embed-relay.mjs before CLI builds.\nexport const EMBEDDED_RELAY_SHA256 = ${JSON.stringify(sha256)};\nexport const EMBEDDED_RELAY_SOURCE = ${JSON.stringify(source)};\n`;
const target = resolve(cliDirectory, "src/generated/relay-artifact.ts");
const current = await readFile(target, "utf8").catch(() => undefined);
if (current !== generated) {
  await writeFile(target, generated, "utf8");
}
